# Generated by Django 6.0.3 on 2026-04-02 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
                ('position_on_machine', models.CharField(max_length=200)),
                ('warehouse_position', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('min_quantity', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.warehouse')),
            ],
        ),
    ]
