# Generated by Django 6.0.3 on 2026-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='barcode',
            new_name='map_position',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='warehouse_position',
            new_name='part_id_barcode',
        ),
        migrations.RemoveField(
            model_name='item',
            name='part_id',
        ),
        migrations.AddField(
            model_name='item',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
