# Generated by Django 6.0.3 on 2026-04-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_barcode_item_map_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
