# Generated by Django 6.0.3 on 2026-04-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_price_item_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='last_change_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
