# Generated by Django 6.0.3 on 2026-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_belt_purpose_item_belt_type_item_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_of_measure',
            field=models.CharField(choices=[('kom', 'PCS (Komad)'), ('m', 'm (Metar)'), ('l', 'l (Litar)'), ('kg', 'kg (Kilogram)'), ('set', 'SET (Komplet)')], default='kom', max_length=10),
        ),
    ]
